import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { initializeIcons } from '@uifabric/icons';
import 'office-ui-fabric-core/dist/css/fabric.min.css';
import './style/app.css';
import App from './App';
// import registerServiceWorker from './registerServiceWorker';
initializeIcons();
ReactDOM.render(<App />, document.getElementById('root'));
// registerServiceWorker();
